DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS portfolio;

CREATE TABLE person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE portfolio (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    FOREIGN KEY(person_id) REFERENCES person(id)
);