DROP TABLE IF EXISTS portfolio;
DROP TABLE IF EXISTS person;

CREATE TABLE person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE portfolio (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    person_id INTEGER, 
    FOREIGN KEY(person_id) REFERENCES person(id)
);
