DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS ministry;

CREATE TABLE person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE ministry (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    FOREIGN KEY(person_id) REFERENCES person(id)
);